name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'
  
permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          show-progress: false
          fetch-depth: 0

      - run: git fetch --tags --force

      - name: Create changelog
        run: |
          git log "$(git describe --tags --abbrev=0 HEAD^)..HEAD" --pretty=%B > CHANGELOG.md

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name : Install Fyne
        run: go install fyne.io/tools/cmd/fyne@latest

      - name: Build
        run: fyne package --release
      # - name: Upload Artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: GoBorderless
      #     path: GoBorderless.exe
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          artifacts: "GoBorderless.exe"
          name: ${{ github.ref_name }}
          generateReleaseNotes: true
          bodyFile: "CHANGELOG.md"
